language: python

python:
   - "3.6"

services:
   - docker

before_install:
   - sudo apt-get update
   - sudo apt-get install python3 python3-pip build-essential
   - sudo apt-get install -y git


install:
   - pip3 install -r requirements.txt
   - pip3 install mock nose parameterized
   - pip3 install git+https://github.com/fairscape/python-auth

script:
  - cd app
  - export NO_AUTH=True
  - python3 -m pytest -v tests/tests.py


after_success:
   - set -e
   - cd ..
   - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD";
   - REPO=jniestroy/object-service
   - docker build -f Dockerfile -t $REPO:latest .;
   - docker push $REPO:latest;
   - echo "Pushed to" $REPO:latest;
